[package]
name = "ppd-egui"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.3.1"
eframe = "0.31.1"
env_logger = "0.11.8"
tokio = { version = "1.45.1", features = ["rt-multi-thread"] }
